/* Automatically generated by po2tbl.sed from a2ps.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"any type", 2},
  {"cannot create file `%s'", 3},
  {"cannot open a pipe on `%s'", 4},
  {"Delegation `%s', from %s to %s\n", 5},
  {"Applications configured for delegation", 6},
  {"`%s' is a directory", 7},
  {"cannot open file `%s'", 8},
  {"cannot get informations on file `%s'", 9},
  {"[%s (%s): 1 page on 1 sheet]\n", 10},
  {"[%s (%s): %d pages on 1 sheet]\n", 11},
  {"[%s (%s): %d pages on %d sheets]\n", 12},
  {"[Total: 1 page on 1 sheet] %s\n", 13},
  {"[Total: %d pages on 1 sheet] %s\n", 14},
  {"[Total: %d pages on %d sheets] %s\n", 15},
  {"[1 line wrapped]\n", 16},
  {"[%d lines wrapped]\n", 17},
  {"[No output produced]\n", 18},
  {"%s, delegated to %s", 19},
  {"[%s (%s): failed.  Ignored]\n", 20},
  {"[%s (unprintable): ignored]\n", 21},
  {"[%s (binary): ignored]\n", 22},
  {"plain", 23},
  {"end-of-line in string constant", 24},
  {"end of line inside a %s", 25},
  {"received signal %d: %s", 26},
  {"heavy", 27},
  {"normal", 28},
  {"none", 29},
  {"yes", 30},
  {"no", 31},
  {"Configuration status of %s %s\n", 32},
  {"Sheets:\n", 33},
  {"\
  medium          = %s%s, %s\n\
  page layout     = %d x %d, %s\n\
  borders         = %s\n\
  file alignment  = %s\n\
  interior margin = %d\n", 34},
  {"portrait", 35},
  {"landscape", 36},
  {"%d characters per line", 37},
  {"%d lines per page", 38},
  {"font size is %gpt", 39},
  {"each line", 40},
  {"each %d lines", 41},
  {"Virtual pages:\n", 42},
  {"\
  number lines         = %s\n\
  format               = %s\n\
  tabulation size      = %d\n\
  non printable format = %s\n", 43},
  {"Headers:\n", 44},
  {"\
  header       = %s\n\
  left footer  = %s\n\
  footer       = %s\n\
  right footer = %s\n\
  left title   = %s\n\
  center title = %s\n\
  right title  = %s\n\
  under lay    = %s\n", 45},
  {"Input:\n", 46},
  {"\
  truncate lines = %s\n\
  interpret      = %s\n\
  end of line    = %s\n\
  encoding       = %s\n\
  document title = %s\n\
  prologue       = %s\n\
  print anyway   = %s\n\
  delegating     = %s\n", 47},
  {"selected automatically", 48},
  {"Pretty-printing:\n", 49},
  {"\
  style sheet     = %s\n\
  highlight level = %s\n\
  strip level     = %d\n", 50},
  {"never make backups", 51},
  {"simple backups of every file", 52},
  {"\
numbered backups of files already numbered,\n\
                            and simple of others", 53},
  {"numbered backups of every file", 54},
  {"Output:\n", 55},
  {"\
  destination     = %s\n\
  version control = %s\n\
  backup suffix   = %s\n", 56},
  {"PostScript:\n", 57},
  {"\
  magic number              = %s\n\
  Printer Description (PPD) = %s\n\
  default PPD               = %s\n\
  page label format         = %s\n\
  number of copies          = %d\n\
  sides per sheet           = %s\n\
  page device definitions   = ", 58},
  {"  statusdict definitions    = ", 59},
  {"  page prefeed              = %s\n", 60},
  {"Internals:\n", 61},
  {"\
  verbosity level     = %d\n\
  file command        = %s\n\
  library path        = \n", 62},
  {"\
Usage: %s [OPTION]... [FILE]...\n\
\n\
Convert FILE(s) or standard input to PostScript.\n\
\n\
Mandatory arguments to long options are mandatory for short options too.\n\
Long options marked with * require a yes/no argument, corresponding\n\
short options stand for `yes'.\n", 63},
  {"Tasks:\n", 64},
  {"\
  --version        display version\n\
  --help           display this help\n\
  --guess          report guessed types of FILES\n\
  --which          report the full path of library files named FILES\n\
  --glob           report the full path of library files matching FILES\n\
  --list=defaults  display default settings and parameters\n\
  --list=TOPIC     detailed list on TOPIC (delegations, encodings, \
features,\n\
                   variables, media, ppd, printers, prologues, \
style-sheets,\n\
                   user-options)\n", 65},
  {"\
After having performed the task, exit successfully.  Detailed lists may\n\
provide additional help on specific features.\n", 66},
  {"Global:\n", 67},
  {"\
  -q, --quiet, --silent      be really quiet\n\
  -v, --verbose[=LEVEL]      set verbosity on, or to LEVEL\n\
  -=, --user-option=OPTION   use the user defined shortcut OPTION\n\
      --debug                enable debugging features\n\
  -D, --define=KEY[:VALUE]   unset variable KEY or set to VALUE\n", 68},
  {"\
  -M, --medium=NAME      use output medium NAME\n\
  -r, --landscape        print in landscape mode\n\
  -R, --portrait         print in portrait mode\n\
      --columns=NUM      number of columns per sheet\n\
      --rows=NUM         number of rows per sheet\n\
      --major=DIRECTION  first fill (DIRECTION=) rows, or columns\n\
  -1, -2, ..., -9        predefined font sizes and layouts for 1.. 9 \
virtuals\n\
  -A, --file-align=MODE  align separate files according to MODE (fill, rank\n\
                         page, sheet, or a number)\n\
  -j, --borders*         print borders around columns\n\
      --margin[=NUM]     define an interior margin of size NUM\n", 69},
  {"\
The options -1.. -9 affect several primitive parameters to set up \
predefined\n\
layouts with 80 columns.  Therefore the order matters: `-R -f40 -2' is\n\
equivalent to `-2'.  To modify the layout, use `-2Rf40', or compose \
primitive\n\
options (`--columns', `--font-size' etc.).\n", 70},
  {"\
      --line-numbers=NUM     precede each NUM lines with its line number\n\
  -C                         alias for --line-numbers=5\n\
  -f, --font-size=SIZE       use font SIZE (float) for the body text\n\
  -L, --lines-per-page=NUM   scale the font to print NUM lines per virtual\n\
  -l, --chars-per-line=NUM   scale the font to print NUM columns per \
virtual\n\
  -m, --catman               process FILE as a man page (same as -L66)\n\
  -T, --tabsize=NUM          set tabulator size to NUM\n\
  --non-printable-format=FMT specify how non-printable chars are printed\n", 71},
  {"Headings:\n", 72},
  {"\
  -B, --no-header        no page headers at all\n\
  -b, --header[=TEXT]    set page header\n\
  -u, --underlay[=TEXT]  print TEXT under every page\n\
  --center-title[=TEXT]  set page title to TITLE\n\
  --left-title[=TEXT]    set left and right page title to TEXT\n\
  --right-title[=TEXT]\n\
  --left-footer[=TEXT]   set sheet footers to TEXT\n\
  --footer[=TEXT]\n\
  --right-footer[=TEXT]\n", 73},
  {"The TEXTs may use special escapes.\n", 74},
  {"\
  -a, --pages[=RANGE]        select the pages to print\n\
  -c, --truncate-lines*      cut long lines\n\
  -i, --interpret*           interpret tab, bs and ff chars\n\
      --end-of-line=TYPE     specify the eol char (TYPE: r, n, nr, rn, any)\n\
  -X, --encoding=NAME        use input encoding NAME\n\
  -t, --title=NAME           set the name of the job\n\
      --stdin=NAME           set the name of the input file stdin\n\
      --print-anyway*        force binary printing\n\
  -Z, --delegate*            delegate files to another application\n\
      --toc[=TEXT]           generate a table of content\n", 75},
  {"\
When delegations are enabled, a2ps may use other applications to handle the\n\
processing of files that should not be printed as raw information, e.g., \
HTML\n\
PostScript, PDF etc.\n", 76},
  {"\
  -E, --pretty-print[=LANG]  enable pretty-printing (set style to LANG)\n\
  --highlight-level=LEVEL    set pretty printing highlight LEVEL\n\
                             LEVEL can be none, normal or heavy\n\
  -g                         alias for --highlight-level=heavy\n\
  --strip-level=NUM          level of comments stripping\n", 77},
  {"\
  -o, --output=FILE          leave output to file FILE.  If FILE is `-',\n\
                             leave output to stdout.\n\
  --version-control=WORD     override the usual version control\n\
  --suffix=SUFFIX            override the usual backup suffix\n\
  -P, --printer=NAME         send output to printer NAME\n\
  -d                         send output to the default printer\n", 78},
  {"\
      --prologue=FILE        include FILE.pro as PostScript prologue\n\
      --ppd[=KEY]            automatic PPD selection or set to KEY\n\
  -n, --copies=NUM           print NUM copies of each page\n\
  -s, --sides=MODE           set the duplex MODE (`1' or `simplex',\n\
                             `2' or `duplex', `tumble')\n\
  -S, --setpagedevice=K[:V]  pass a page device definition to output\n\
      --statusdict=K[:[:]V]  pass a statusdict definition to the output\n\
  -k, --page-prefeed         enable page prefeed\n\
  -K, --no-page-prefeed      disable page prefeed\n", 79},
  {"\
By default a2ps is tuned to do what you want to, so trust it.  To pretty\n\
print the content of the `src' directory and a table of content, and send \
the\n\
result to the printer `lw',\n\
\n\
    $ a2ps -P lw --toc src/*\n\
\n\
To process the files `sample.ps' and `sample.html' and display the result,\n\
\n\
    $ a2ps -P display sample.ps sample.html\n\
\n\
To process a mailbox in 4 up,\n\
\n\
    $ a2ps -=mail -4 mailbox\n\
\n\
To print as a booklet on the default printer, which is Duplex capable,\n\
\n\
    $ a2ps -=book paper.dvi.gz -d\n", 80},
  {"\
News, updates and documentation: visit \
http://www.inf.enst.fr/~demaille/a2ps/.\n", 81},
  {"Report bugs to <bug-a2ps@gnu.org>.\n", 82},
  {"\
Copyright (c) 1988-1993 Miguel Santana\n\
Copyright (c) 1995-2000 Akim Demaille, Miguel Santana", 83},
  {"Table of Content", 84},
  {"cannot process `%s' which requires a2ps version %s", 85},
  {"unexpected character `%c'", 86},
  {"too many includes", 87},
  {"no key defined for `%s'", 88},
  {"cannot find file `%s'", 89},
  {"automatic style selection cancelled", 90},
  {"cannot compile regular expression `%s': %s", 91},
  {"Known Style Sheets", 92},
  {"cannot find style sheet `%s': using plain style", 93},
  {"unknown encoding `%s', ignored", 94},
  {"Copyright (C) 1999 Free Software Foundation, Inc.", 95},
  {"Written by %s.\n", 96},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 97},
  {"invalid version number `%s'", 98},
  {"space (i.e., ` ')", 99},
  {"octal (i.e., `\\001' etc.)", 100},
  {"hexadecimal (i.e., `\\x0a' etc.)", 101},
  {"caret (i.e., `^C', `M-^C' etc.)", 102},
  {"emacs (i.e., `C-c', `M-C-c' etc.)", 103},
  {"question-mark (i.e., `?')", 104},
  {"write error", 105},
  {"invalid option `%s'", 106},
  {"missing argument for `%s'", 107},
  {"invalid definition for printer `%s': %s", 108},
  {"Unknown Printer", 109},
  {"Default Printer", 110},
  {"invalid variable identifier `%s'", 111},
  {"obsolete `%s' entry.  Ignored", 112},
  {"Known Encodings", 113},
  {"incomplete knowledge of faces", 114},
  {"cannot close directory `%s'", 115},
  {"invalid argument `%s' for `%s'", 116},
  {"Valid arguments are integers n such that: %s\n", 117},
  {"Valid arguments are floats f such that: %s\n", 118},
  {"unknown encoding `%s'", 119},
  {"rows first", 120},
  {"columns first", 121},
  {"unknown medium `%s'", 122},
  {"Known Media", 123},
  {"Name", 124},
  {"dimensions", 125},
  {"Known Variables", 126},
  {"Printed by %s", 127},
  {"Printed by %s from %s", 128},
  {"cannot get current working directory", 129},
  {"%s: too long argument for %s escape", 130},
  {"%b %d, %y", 131},
  {"%A %B %d, %Y", 132},
  {"%s: unknown `%s' escape `%c' (%d)", 133},
  {"Page %d", 134},
  {"Page %d/%c", 135},
  {"%s: missing `%c' for %s%c escape", 136},
  {"%s: invalid separator `%s%c' for `%s' escape", 137},
  {"%s: invalid argument for %s%c escape", 138},
  {"Page %d/%d", 139},
  {"output command", 140},
  {"Try `%s --help' for more information.\n", 141},
  {"invalid face `%s'", 142},
  {"`%s' with no matching `%s'", 143},
  {"Known Fonts", 144},
  {"\
\n\
  None.\n", 145},
  {"Known PostScript Printer Descriptions", 146},
  {"invalid interval `%s'", 147},
  {"no command for the `%s' (%s%s)", 148},
  {"sent to the standard output", 149},
  {"sent to the default printer", 150},
  {"saved into the file `%s'", 151},
  {"sent to the printer `%s'", 152},
  {"Known Outputs (Printers, etc.)", 153},
  {"Known Prologues", 154},
  {"font %f too big", 155},
  {"`%s' is a binary file, printing aborted", 156},
  {"`", 157},
  {"'", 158},
  {"user", 159},
  {"Unknown User", 160},
  {"unknown user option `%s'", 161},
  {"Known User Options", 162},
  {"Memory exhausted", 163},
  {"cannot rename file `%s' as `%s'", 164},
  {"restored file `%s'", 165},
  {"invalid argument %s for `%s'", 166},
  {"ambiguous argument %s for `%s'", 167},
  {"Valid arguments are:", 168},
  {"Unknown system error", 169},
  {"%s: option `%s' is ambiguous\n", 170},
  {"%s: option `--%s' doesn't allow an argument\n", 171},
  {"%s: option `%c%s' doesn't allow an argument\n", 172},
  {"%s: option `%s' requires an argument\n", 173},
  {"%s: unrecognized option `--%s'\n", 174},
  {"%s: unrecognized option `%c%s'\n", 175},
  {"%s: illegal option -- %c\n", 176},
  {"%s: invalid option -- %c\n", 177},
  {"%s: option requires an argument -- %c\n", 178},
  {"%s: option `-W %s' is ambiguous\n", 179},
  {"%s: option `-W %s' doesn't allow an argument\n", 180},
};

int _msg_tbl_length = 180;
